export const movies = [
  {
    id: 1,
    title: "Inception",
    genre: "Sci-Fi",
    rating: 8.8,
    year: 2010,
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    type: "movie",
  },
  {
    id: 2,
    title: "The Dark Knight",
    genre: "Action",
    rating: 9.0,
    year: 2008,
    actors: ["Christian Bale", "Heath Ledger"],
    type: "movie",
  },
  {
    id: 3,
    title: "Interstellar",
    genre: "Sci-Fi",
    rating: 8.6,
    year: 2014,
    actors: ["Matthew McConaughey", "Anne Hathaway"],
    type: "movie",
  },
  {
    id: 4,
    title: "Breaking Bad",
    genre: "Crime",
    rating: 9.5,
    year: 2008,
    actors: ["Bryan Cranston", "Aaron Paul"],
    type: "tv",
  },
  {
    id: 5,
    title: "Stranger Things",
    genre: "Fantasy",
    rating: 8.7,
    year: 2016,
    actors: ["Millie Bobby Brown", "David Harbour"],
    type: "tv",
  },
  {
    id: 6,
    title: "The Matrix",
    genre: "Action",
    rating: 8.7,
    year: 1999,
    actors: ["Keanu Reeves", "Laurence Fishburne"],
    type: "movie",
  },
];
